@AIDiffReviewService_HostAddress = https://localhost:7259

GET {{AIDiffReviewService_HostAddress}}/health
Accept: application/json

###

GET {{AIDiffReviewService_HostAddress}}/spec
Accept: application/json

###

POST {{AIDiffReviewService_HostAddress}}/v1/reviews
Authorization: Bearer Token
Content-Type: application/json

{ "diff": "--- a/app.js\n+++ b/app.js\n@@ -1,0 +1,3 @@\n+eval(x);\n+console.log(y);\n+// TODO: fix\n" }

###

GET {{AIDiffReviewService_HostAddress}}/v1/reviews/jobId
Authorization: Bearer Token
Accept: application/json